// Package crypto implements QUIC header protection per RFC 9001 §5.4.
//
// Header protection conceals the Packet Number field and certain bits of the
// first byte of QUIC packets from on-path observers.
//
// Fields protected:
//   - Long headers: 4 least significant bits of byte 0 (reserved bits + PN length)
//   - Short headers: 5 least significant bits of byte 0 (reserved bits + Key Phase + PN length)
//   - Packet Number field: masked with remaining mask bytes
//
// The header protection key does NOT change during a key update (RFC 9001 §5.4).
// This ensures the Key Phase bit is protected even after key rotation.
package crypto

import (
	"crypto/aes"
	"encoding/binary"
	"errors"
	"fmt"
)

// HeaderProtectionSampleLen is the length of the ciphertext sample used
// for header protection mask generation (RFC 9001 §5.4.2).
const HeaderProtectionSampleLen = 16

// HeaderProtectionMaskLen is the length of the mask generated by the
// header protection function (5 bytes: 1 byte for first byte + 4 bytes for PN).
const HeaderProtectionMaskLen = 5

// LongHeaderHPMask is the mask applied to the first byte of long headers (4 bits).
const LongHeaderHPMask byte = 0x0f

// ShortHeaderHPMask is the mask applied to the first byte of short headers (5 bits).
const ShortHeaderHPMask byte = 0x1f

// headerProtectionAES implements header protection using AES-ECB (RFC 9001 §5.4.3).
// The mask is generated by encrypting the 16-byte ciphertext sample with AES-ECB.
//
//   mask = AES-ECB(hp_key, sample)
func headerProtectionAES(hpKey, sample []byte) ([]byte, error) {
	if len(sample) != HeaderProtectionSampleLen {
		return nil, fmt.Errorf("crypto: sample must be %d bytes, got %d", HeaderProtectionSampleLen, len(sample))
	}

	block, err := aes.NewCipher(hpKey)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to create AES cipher for header protection: %w", err)
	}

	mask := make([]byte, HeaderProtectionSampleLen)
	block.Encrypt(mask, sample)
	return mask[:HeaderProtectionMaskLen], nil
}

// generateHeaderProtectionMask generates the 5-byte mask for header protection.
func generateHeaderProtectionMask(hpKey, sample []byte, suiteID CipherSuiteID) ([]byte, error) {
	cs, ok := GetCipherSuite(suiteID)
	if !ok {
		return nil, fmt.Errorf("crypto: unknown cipher suite 0x%04x", suiteID)
	}

	switch cs.HeaderProtection {
	case "AES-ECB":
		return headerProtectionAES(hpKey, sample)
	case "ChaCha20":
		return nil, errors.New("crypto: ChaCha20 header protection not yet implemented")
	default:
		return nil, fmt.Errorf("crypto: unknown header protection type: %s", cs.HeaderProtection)
	}
}

// ApplyHeaderProtection applies header protection to a packet (RFC 9001 §5.4, Figure 6).
//
// This function is called AFTER AEAD encryption, when the packet payload
// has been replaced with ciphertext. The header protection mask is derived
// from the ciphertext.
//
// Parameters:
//   - packet: the packet with AEAD-encrypted payload (will be modified in place)
//   - pnOffset: byte offset of the packet number field
//   - pnLen: encoded packet number length (1-4 bytes)
//   - isLongHeader: true for long headers, false for short headers
//   - hpKey: header protection key
//   - suiteID: cipher suite ID (determines mask generation method)
func ApplyHeaderProtection(packet []byte, pnOffset, pnLen int, isLongHeader bool, hpKey []byte, suiteID CipherSuiteID) error {
	// The sample is taken from the ciphertext, starting 4 bytes after the
	// packet number field (assuming 4-byte PN for sampling, RFC 9001 §5.4.2).
	sampleOffset := pnOffset + 4 // PN is assumed to be 4 bytes for sampling
	sampleEnd := sampleOffset + HeaderProtectionSampleLen

	if len(packet) < sampleEnd {
		return fmt.Errorf("crypto: packet too short for header protection sample (need %d bytes, have %d)",
			sampleEnd, len(packet))
	}

	sample := packet[sampleOffset:sampleEnd]

	mask, err := generateHeaderProtectionMask(hpKey, sample, suiteID)
	if err != nil {
		return err
	}

	// Apply mask to first byte
	if isLongHeader {
		// Long header: mask 4 least significant bits
		packet[0] ^= mask[0] & LongHeaderHPMask
	} else {
		// Short header: mask 5 least significant bits
		packet[0] ^= mask[0] & ShortHeaderHPMask
	}

	// Apply mask to packet number field
	for i := 0; i < pnLen; i++ {
		packet[pnOffset+i] ^= mask[1+i]
	}

	return nil
}

// RemoveHeaderProtection removes header protection from a packet (RFC 9001 §5.4).
//
// This function is called BEFORE AEAD decryption. After removing header
// protection, the packet number can be fully reconstructed and used as the
// AEAD nonce.
//
// Note: Before removing header protection, the packet number length (pnLen)
// is derived from the low 2 bits of byte 0. Since those bits are protected,
// we must use the protected value to determine pnLen, then remove the
// protection. This is correct because the PN length bits are the same as
// the unprotected value — the mask is applied to the same bits.
//
// Parameters:
//   - packet: the protected packet (will be modified in place)
//   - pnOffset: byte offset of the packet number field
//   - pnLen: encoded packet number length (1-4 bytes)
//   - isLongHeader: true for long headers, false for short headers
//   - hpKey: header protection key
//   - suiteID: cipher suite ID
func RemoveHeaderProtection(packet []byte, pnOffset, pnLen int, isLongHeader bool, hpKey []byte, suiteID CipherSuiteID) error {
	// The sample is taken from the ciphertext (which is still protected by
	// header protection — but the sample bytes are after the PN, so they
	// are not affected by header protection mask. Only the first byte's low
	// bits and the PN field are masked. The sample starts 4 bytes after pnOffset.)
	sampleOffset := pnOffset + 4
	sampleEnd := sampleOffset + HeaderProtectionSampleLen

	if len(packet) < sampleEnd {
		return fmt.Errorf("crypto: packet too short for header protection sample (need %d bytes, have %d)",
			sampleEnd, len(packet))
	}

	sample := packet[sampleOffset:sampleEnd]

	mask, err := generateHeaderProtectionMask(hpKey, sample, suiteID)
	if err != nil {
		return err
	}

	// Remove mask from first byte
	if isLongHeader {
		packet[0] ^= mask[0] & LongHeaderHPMask
	} else {
		packet[0] ^= mask[0] & ShortHeaderHPMask
	}

	// Remove mask from packet number field
	for i := 0; i < pnLen; i++ {
		packet[pnOffset+i] ^= mask[1+i]
	}

	return nil
}

// CalculatePNOffsetLong calculates the packet number offset for long headers.
//
// For long headers (RFC 9001 §5.4.2):
//   pn_offset = 7 + len(DCID) + len(SCID) + len(payload_length)
// For Initial packets: pn_offset += len(token_length) + len(token)
func CalculatePNOffsetLong(dcidLen, scidLen int, isInitial bool, token []byte) int {
	offset := 7 + dcidLen + scidLen
	// payload_length is a varint, we need to know its encoded length
	// For simplicity, this is calculated by the caller and passed as part of the offset.
	// Here we add the token length for Initial packets.
	if isInitial {
		// token_length varint + token bytes
		tokenLenBytes := varintLen(uint64(len(token)))
		offset += tokenLenBytes + len(token)
	}
	return offset
}

// CalculatePNOffsetShort calculates the packet number offset for short headers.
//
// For short headers (RFC 9001 §5.4.2):
//   pn_offset = 1 + len(DCID)
func CalculatePNOffsetShort(dcidLen int) int {
	return 1 + dcidLen
}

// varintLen returns the number of bytes needed to encode a varint value.
func varintLen(v uint64) int {
	switch {
	case v <= 63:
		return 1
	case v <= 16383:
		return 2
	case v <= 1073741823:
		return 4
	default:
		return 8
	}
}

// PacketNumberLength returns the encoded packet number length from the
// low 2 bits of the first byte of a protected or unprotected packet.
// This works for both long and short headers (RFC 9000 §17.2, §17.3).
func PacketNumberLength(firstByte byte) int {
	return int(firstByte&0x03) + 1
}

// GetSampleOffset returns the offset of the header protection sample
// in the packet. The sample is always 16 bytes starting at pnOffset + 4.
func GetSampleOffset(pnOffset int) int {
	return pnOffset + 4
}

// MinimumPacketLen returns the minimum packet length required for header
// protection. The packet must be long enough to contain the sample (16 bytes)
// starting 4 bytes after the packet number offset.
func MinimumPacketLen(pnOffset int) int {
	return pnOffset + 4 + HeaderProtectionSampleLen
}

// binaryOrder is used for internal byte ordering utilities.
var _ = binary.BigEndian
